name: Lua Linter

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Lua environment
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks

      - name: Setup Lua environment
        run: sudo luarocks install luacheck

      - name: Run luacheck
        run: luacheck . --config .luacheckrc --no-color
