name: Lua Linter

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Luacheck linter
        uses: lunarmodules/luacheck@v1
        with:
          args: KeyRoller.lua
        env:
          DEFAULT_BRANCH: "trunk"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
