name: Release

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

env:
  CF_API_KEY: ${{ secrets.CF_API_KEY }}
  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }} 

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment: release
    steps:
      - name: Clone project
        uses: actions/checkout@v1
        with:
          fetch-depth: 20

      - name: Generate Changelog file
        run: chmod +x genchangelog.sh && ./genchangelog.sh

      - name: Package and release
        uses: BigWigsMods/packager@v2
        with:
          args: -g retail
